name: Build
on:
  push:
    branches:
      - main
jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            gradle_args: publishKotlinMultiplatformPublicationToMavenLocal publishJvmPublicationToMavenLocal
          - os: ubuntu-latest
            gradle_args: publishMingwX64PublicationToMavenLocal publishLinuxX64PublicationToMavenLocal
          - os: macos-latest
            gradle_args: publishMacosX64PublicationToMavenLocal publishMacosArm64PublicationToMavenLocal publishIosX64PublicationToMavenLocal publishIosArm64PublicationToMavenLocal
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: liberica
          java-version: 17
      - name: Build using gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ${{ matrix.gradle_args }}
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/**/*
  publish:
    needs: build
    runs-on: ubuntu-latest
    env:
      SIGNING_SECRET_KEY: ${{ secrets.SIGNING_SECRET_KEY }}
      SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build
      - uses: actions/setup-java@v3
        with:
          distribution: liberica
          java-version: 17
      - name: Publish to staging repo
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publishAllPublicationsToSonatypeRepository
