name: Release project

on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: macos-latest
    env:
      SIGNING_SECRET_KEY: ${{ secrets.SIGNING_SECRET_KEY }}
      SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Cache konan
        uses: actions/cache@v3
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan
      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assemble
      - name: Publish
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish closeAndReleaseStagingRepository
