name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            gradle_args: publishJvmPublicationToSonatypeRepository publishKotlinMultiplatformPublicationToSonatypeRepository
          - os: ubuntu-latest
            gradle_args: publishLinuxX64PublicationToSonatypeRepository
          - os: ubuntu-latest
            gradle_args: publishMingwX64PublicationToSonatypeRepository
          - os: macos-latest
            gradle_args: publishIosArm64PublicationToSonatypeRepository
          - os: macos-latest
            gradle_args: compileKotlinIosX64 publishIosX64PublicationToSonatypeRepository
          - os: macos-latest
            gradle_args: publishIosSimulatorArm64PublicationToSonatypeRepository
          - os: macos-latest
            gradle_args: publishMacosX64PublicationToSonatypeRepository
          - os: macos-latest
            gradle_args: publishMacosArm64PublicationToSonatypeRepository
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: liberica
          java-version: 17
      - name: Build using gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ${{ matrix.gradle_args }}
