name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: liberica
          java-version: 17
      - name: Publish multiplatform metadata to Maven Local
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publishKotlinMultiplatformPublicationToMavenLocal
      - name: Check metadata
        run: cat ~/.m2/repository/org/ton/ton-kotlin/0.2.12/ton-kotlin-0.2.12.module
