name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            gradle_args: compileKotlinJvm
          - os: ubuntu-latest
            gradle_args: compileKotlinLinuxX64
          - os: ubuntu-latest
            gradle_args: compileKotlinMingwX64
          - os: macos-latest
            gradle_args: compileKotlinIosArm64
          - os: macos-latest
            gradle_args: compileKotlinIosX64
          - os: macos-latest
            gradle_args: compileKotlinIosSimulatorArm64
          - os: macos-latest
            gradle_args: compileKotlinMacosX64
          - os: macos-latest
            gradle_args: compileKotlinMacosArm64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: liberica
          java-version: 17
      - name: Build using gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ${{ matrix.gradle_args }}
