name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            gradle_args: jvmMainClasses
          - os: ubuntu-latest
            gradle_args: compileKotlinLinuxX64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: liberica
          java-version: 17
      - name: Publish multiplatform metadata to Maven Local
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ${{ gradle_args }}
