name: Test
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: liberica
          java-version: 1.8
      - name: Build using gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: jvmTest
